Feat/wrapper notification center
rees46/android-sdk pull request #52
Opened 2024-08-14 06:50 UTC by xeewii

https://github.com/rees46/planning/issues/414

2024-08-15 20:33 UTC, TorinAsakura requested changes
Если коротко, то с такими понятиями как:
- репозиторий
- юзкейс
- домен
- имплементор

Ты не разобралась. Дальше смотреть не стал, с этим бы разобраться.

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +        params.put(SHOP_ID_PARAMS_FIELD, shopId)
кажется такие вещи как SHOP_ID_PARAMS_FIELD и те, что ниже лучше делать в виде enum

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    }
```suggestion
    private fun addOptionalParam(params: JSONObject, key: String, value: String?) {
    value?.let { params.put(key, it) }
}

internal fun addParams(
    params: JSONObject,
    notificationSource: NotificationSource?,
    isSecret: Boolean = false
): JSONObject {
    params.put(SHOP_ID_PARAMS_FIELD, shopId)

    if (isSecret) {
        params.put(SHOP_SECRET_KEY_PARAMS_FIELD, shopSecretKey)
    }

    addOptionalParam(params, DID_PARAMS_FIELD, getDid())
    addOptionalParam(params, SEANCE_PARAMS_FIELD, getSid())
    params.put(SEGMENT_PARAMS_FIELD, segment)
    params.put(STREAM_PARAMS_FIELD, stream)

    notificationSource?.let {
        val notificationObject = JSONObject()
            .put(SOURCE_FROM_FIELD, it.type)
            .put(SOURCE_CODE_FIELD, it.id)
        params.put(SOURCE_PARAMS_FIELD, notificationObject)
    }

    return params
}
```

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    }
полагаю мы должны предотвращать процесс разрастания подобных методов ещё в зародыше

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    private var userAgent: String = ""
кажется эти вещи надо валидировать при инициализации

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    fun initialize(
Если shopId, shopSecretKey и остальные, известны на этапе создания объекта, кажется, лучше использовать конструктор для их инициализации вместо отдельного метода initialize. Это сделает объект более иммутабельным и безопасным для многопоточного использования.

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsRepositoryImpl.kt
Сейчас выглядит так, будто репозиторий практически полностью делегирует свою функциональность. Это делает его существование в некоторой степени избыточным, если он не добавляет никакой дополнительной логики или абстракции. В такой ситуации стоит задаться вопросом: "Нужен ли этот репозиторий вообще, если его функции не отличаются от методов источника данных?"

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    }
```suggestion
private fun addOptionalParam(params: JSONObject, key: String, value: String?) {
    value?.let { params.put(key, it) }
}

internal fun addParams(
    params: JSONObject,
    notificationSource: NotificationSource?,
    isSecret: Boolean = false
): JSONObject {
    params.put(SHOP_ID_PARAMS_FIELD, shopId)

    if (isSecret) {
        params.put(SHOP_SECRET_KEY_PARAMS_FIELD, shopSecretKey)
    }

    addOptionalParam(params, DID_PARAMS_FIELD, getDid())
    addOptionalParam(params, SEANCE_PARAMS_FIELD, getSid())
    params.put(SEGMENT_PARAMS_FIELD, segment)
    params.put(STREAM_PARAMS_FIELD, stream)

    notificationSource?.let {
        val notificationObject = JSONObject()
            .put(SOURCE_FROM_FIELD, it.type)
            .put(SOURCE_CODE_FIELD, it.id)
        params.put(SOURCE_PARAMS_FIELD, notificationObject)
    }

    return params
}
```

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    }
кажется такие методы стоит защищать от возможного разрастания ещё на старте

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +        params.put(SHOP_ID_PARAMS_FIELD, shopId)
стринги по типу SHOP_ID_PARAMS_FIELD нужно выносить в виде enum или же в отдельный объект для параметров

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    private var userAgent: String = ""
кажется, если от этих вещей зависит вся дальнейшая работа - их надо валидировать

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    fun initialize(
Если shopId, shopSecretKey и другие параметры известны на этапе создания объекта, можно использовать конструктор для их инициализации вместо отдельного метода initialize. Это сделает объект более иммутабельным и безопасным для многопоточного использования.

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/repositories/NetworkRepository.kt
ещё раз - репозиторий отвечает за абстрагирование источников данных, будь то база данных, кэш или API, и предоставление бизнес-логике готовых данных, а в данном случае данный интерфейс больше похож на низкоуровневый сетевой клиент, который управляет отправкой и получением сетевых запросов, а не на репозиторий

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/repositories/NetworkRepository.kt
Репозиторий в Чистой архитектуре должен предоставлять данные в виде объектов доменной модели, а не управлять потоками или выполнять низкоуровневые сетевые запросы. Эти задачи больше подходят для сетевых клиентов или дэйта сорсов

2024-08-15 20:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/repositories/NetworkRepository.kt
Далее, в интерфейсе нет ничего, что напрямую связано с бизнес-логикой. Все методы сосредоточены на низкоуровневых операциях, таких как отправка и получение HTTP-запросов, поэтому не очень понятно, почему это репозиторий

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/features/recommendation/RecommendationManagerImpl.kt
Сделала

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/features/track_event/TrackEventManagerImpl.kt
Изменила

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/network/NetworkDataSource.kt
> +    internal var baseUrl: String = ""
Убрала baseUrl в конструктор

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/notification/NotificationRepositoryImpl.kt
>      }
Только в одном месте это делаю, а так низко она, потому что приватный метод

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +        params.put(SHOP_ID_PARAMS_FIELD, shopId)
Вынесла в енам

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    }
Приняла изменения

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    private var userAgent: String = ""
Как это делать?
Если с shopId и shopSecretKey что-то не так, то будет ошибка от сдк с тем, что данные магазина не верные
Остальное может быть любым же

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    fun initialize(
Вынесла в конструктор

2024-08-16 07:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsRepositoryImpl.kt
Да, сейчас это скорее прокси, но чтобы в юзкейсы не пихать сразу дата соурсе, всё-таки оставила эту прослойку

2024-08-16 07:57 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    }
Приняла изменения

2024-08-16 07:58 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +        params.put(SHOP_ID_PARAMS_FIELD, shopId)
Вынесла в енам

2024-08-16 07:58 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    fun initialize(
Вынесла в конструктор

2024-08-16 07:59 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/user/UserSettingsDataSource.kt
> +    private var userAgent: String = ""
Тот же вопрос: 
Как это делать?
Если с shopId и shopSecretKey что-то не так, то будет ошибка от сдк с тем, что данные магазина не верные
Остальное может быть любым же

2024-08-16 08:07 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/notification/NotificationRepositoryImpl.kt
> +
Не понимаю, как тут билдер поможет. Если бы мы где-то в одном месте потом использовали эти параметры, то другое дело, а так будто бессмысленно.
А так укоротила метод с твоими изменениями

2024-08-16 08:15 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/network/NetworkRepositoryImpl.kt
Со всем согласна, мне просто нужно вынести работу с сетью, чтобы можно было новый код писать независимо, поэтому это был просто перенос кода.
Завела задачу на изменения https://github.com/rees46/planning/issues/1483

2024-08-16 08:16 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/repositories/NetworkRepository.kt
Согласна со всем, что в репозитории нетворка всё напихано, завела задачу на изменение https://github.com/rees46/planning/issues/1483

2024-08-19 20:02 UTC, TorinAsakura requested changes

2024-08-19 20:02 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/utils/EnumUtils.kt
> +    inline fun <reified T : Enum<T>> getEnumsString(enums: EnumSet<T>): String {
```suggestion
inline fun <reified T : Enum<T>> getEnumsString(enums: EnumSet<T>): String {
    return enums.joinToString(",") { it.toString() }
}
```

не?

2024-08-20 06:49 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/responses/notifications/Statistics.kt
С суффиксом Response - это ответ, который мы пользователю отдаем, а остальные классы уже внутренние ответа, названы по тому, как в json'е названы

2024-08-20 06:58 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/responses/SDKError.kt
> +data class SDKError(
Потому что это ответ для пользователя)
Переименовала в SDKErrorResponse

2024-08-20 07:06 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/di/DataSourcesModule.kt
> +        @Singleton
Да, точно. Спасибо, убрала

2024-08-20 07:07 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/di/DataSourcesModule.kt
> +    @AssistedFactory
У меня разбито на модули по другой логике: модули для DataSource, Models и Repositories

2024-08-20 07:10 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/di/DataSourcesModule.kt
> +    @AssistedFactory
Так в конструкторе UserSettingsDataSource аргументы также именованные с помощью @Assisted...
Или ты что-то другое имеешь в виду?

P.S. без именований аргументов одновременно и здесь и в конструкторе сборка даже не соберется)

2024-08-20 07:18 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/utils/EnumUtils.kt
> +    inline fun <reified T : Enum<T>> getEnumsString(enums: EnumSet<T>): String {
Да, спасибо)
Приняла изменения

2024-08-20 07:20 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/models/params/GetAllNotificationsParams.enum.kt
> +enum class GetAllNotificationsParams(val value: String) {
Приняла изменения

2024-08-20 08:04 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/notification/NotificationRepositoryImpl.kt
> +    override fun getAllNotificationsParams(
> Использование addOptionalParam для добавления параметров — норм, но если таких параметров будет много, полагаю тут больше подойдёт билдер-паттерн для параметров запроса

Я всё ещё не поняла, как тут использовать билдер. Хотелось бы либо пример, либо я в будущем когда в очередной раз буду писать подобный код приду к тому, как его здесь использовать)

2024-08-20 08:05 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/notification/NotificationRepositoryImpl.kt
> +    override fun getAllNotificationsParams(
> В целом, я не очень понимаю зачем ты делаешь руками, когда у нас уже в проекте используется тот же самый gson

Что значит руками? Не совсем понимаю, как иначе сделать

2024-08-20 08:09 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/usecases/notification/GetAllNotificationsUseCase.kt
> +    fun invoke(
У меня нет повторяющейся логики, я один из инвоков использую в другом

2024-08-20 08:19 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/usecases/notification/GetAllNotificationsUseCase.kt
> +                        val getAllNotificationsResponse = Gson().fromJson(it.toString(), GetAllNotificationsResponse::class.java)
Вынесла создание листенера со всеми обработками в репозиторий

2024-08-20 08:22 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/usecases/userSettings/UpdateUserSettingsValueUseCase.kt
> +class UpdateUserSettingsValueUseCase @Inject constructor(
Да, сейчас это просто прокси, чтобы напрямую из сдк не вызывать репозитории.
Вообще после вынесения оставшейся логики в юзкейсы этот эзкейс возможно вообще удалится, ибо будет не нужен.
Проверок сюда никаких не могу добавить, ибо нет ограничений на задаваемые значения. Ну кроме null, которого и так не может быть)

2024-08-20 08:24 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/di/RepositoriesModule.kt
> +    abstract fun bindUserRepository(impl: UserSettingsRepositoryImpl): UserSettingsRepository
Ой, артефакт ренейминга - не заметила(
Переимновала

2024-08-20 08:28 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/di/RepositoriesModule.kt
> +    @Singleton
Что значит в неоднородном виде?
А так Singleton для UserSettingsRepository и NetworkRepository нужны, т.к. DataSource я создаю в них теперь через фабрику

2024-08-20 08:37 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/params/NotificationChannel.kt
> +    infix fun and(other: NotificationChannel): EnumSet<NotificationChannel> =
Моя такая реализация сделана для того, чтобы пользователь мог спокойно написать вот так и было всё понятно:
![image](https://github.com/user-attachments/assets/039afbfb-fe8d-41f4-8620-00f3f4e23254)
unionWith здесь будет не так красиво смотреться

2024-08-20 08:42 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/params/NotificationChannel.kt
> +    NotificationChannels.of(other, *this.toTypedArray())
Решила удалить вообще эту функцию за ненадобностью, а использовать задуманный функционал можно как в выше комментарии

2024-08-20 08:47 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/params/NotificationChannel.kt
> +    override fun toString(): String {
Там по-особенному эти типы сериализуются - через запятые, в одну строку - так что кажется нужно оставить в таком виде

2024-08-20 09:05 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/network/NetworkDataSource.kt
> +        internal const val TWO_DAYS_MILLISECONDS  = 60 * 60 * 24 * 2 * 1000
Вынесла значение в TimeUtils, использовав Duration. Здесь вернула отражающее суть название

2024-08-20 09:06 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/usecases/network/AddTaskToQueueUseCase.kt
> +class AddTaskToQueueUseCase @Inject constructor(
А что здесь можно валидировать и обрабатывать...

2024-08-20 09:11 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/di/DataSourcesModule.kt
>  }
Я не совсем разобралась с тем, как это сделать для фабрик, поэтому создала отдельную задачу на это, чтобы не растягивать эту задачу и разобраться полноценно - https://github.com/rees46/planning/issues/1510

2024-08-20 09:12 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/params/NotificationChannel.kt
> +infix fun EnumSet<NotificationChannel>.and(other: NotificationChannel): EnumSet<NotificationChannel> =
https://github.com/rees46/android-sdk/pull/52#discussion_r1722927655

2024-08-20 09:56 UTC, xeewii commented on personalization-sdk/src/main/kotlin/com/personalization/api/params/NotificationChannel.kt
> +    NotificationChannels.of(other, *this.toTypedArray())
Переделала функцию, вынесла в утилиты

2024-08-20 21:53 UTC, TorinAsakura approved these changes

2024-08-20 21:53 UTC, merged