Feat/logging token requests
rees46/android-sdk pull request #59
Opened 2024-09-17 16:41 UTC by DanielGreenEngineer

- https://github.com/rees46/planning/issues/272

2024-09-17 19:41 UTC, TorinAsakura requested changes

2024-09-18 08:51 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/RegisterManager.kt
> +                        debug("Failed to send push token. Code: $code, Message: $msg")
Вернул преждние логи, и заменил дебаг логи, на информационные

2024-09-18 08:51 UTC, DanielGreenEngineer commented
<img width="1459" alt="Screenshot 2024-09-18 at 10 49 38 AM" src="https://github.com/user-attachments/assets/5be9a646-6e37-48c1-9163-a6dc510275aa">

2024-09-18 14:55 UTC, TorinAsakura approved these changes

2024-09-18 14:56 UTC, merged