Feat/customizing in app notification
rees46/android-sdk pull request #70
Opened 2024-10-04 15:58 UTC by DanielGreenEngineer

- https://github.com/rees46/planning/issues/1661

2024-10-09 21:46 UTC, TorinAsakura requested changes

2024-10-09 21:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/utils/button/ButtonPressingAnimation.kt
> +package com.personalization.inAppNotification.utils.button
это не утилиты, это personalization-sdk/src/main/kotlin/com/personalization/ui/animation/button/ButtonPressAnimation.kt

2024-10-09 21:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/utils/button/ButtonPressingAnimation.kt
> +}
```suggestion
import android.view.View
import android.view.animation.AccelerateDecelerateInterpolator

fun View.addPressEffectDeclarative(
    scaleDown: Float = 0.9f,
    duration: Long = 150L
) {
    setOnClickListener {
        // Плавное возвращение к оригинальному размеру после клика
        this.animate().scaleX(1f).scaleY(1f)
            .setDuration(duration)
            .setInterpolator(AccelerateDecelerateInterpolator())
            .start()
    }

    // Анимация нажатия
    this.setOnTouchListener { _, event ->
        when (event.action) {
            MotionEvent.ACTION_DOWN -> {
                this.animate().scaleX(scaleDown).scaleY(scaleDown)
                    .setDuration(duration)
                    .setInterpolator(AccelerateDecelerateInterpolator())
                    .start()
            }
            MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                this.animate().scaleX(1f).scaleY(1f)
                    .setDuration(duration)
                    .setInterpolator(AccelerateDecelerateInterpolator())
                    .start()
            }
        }
        false
    }
}
```

2024-10-09 21:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/utils/button/ButtonPressingAnimation.kt
> +}
ну и я такой чтобы поьтихоньку это переводить на наш uikit или на jetpack

2024-10-09 21:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/view/component/text/AlertText.kt
> +class AlertText @JvmOverloads constructor(
алёрт это всё-таки состояние, но никак не компонент верхнего уровня

2024-10-09 21:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/view/component/button/AlertButton.kt
> +class AlertButton @JvmOverloads constructor(
аналогично

2024-10-11 16:24 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/utils/button/ButtonPressingAnimation.kt
> +package com.personalization.inAppNotification.utils.button
Согласен, вынес в отдельный пакет

2024-10-11 16:25 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/view/component/text/AlertText.kt
> +class AlertText @JvmOverloads constructor(
Поддерживаю. Переименов просто в текст, так как мы опираемся на импорты

2024-10-11 16:25 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/inAppNotification/view/component/button/AlertButton.kt
> +class AlertButton @JvmOverloads constructor(
Так же переименовал

2024-10-11 16:50 UTC, TorinAsakura approved these changes

2024-10-11 16:51 UTC, merged