feat: Adding filter guide
rees46/android-sdk pull request #71
Opened 2024-10-04 15:59 UTC by DanielGreenEngineer

- https://github.com/rees46/planning/issues/416

2024-10-31 18:54 UTC, TorinAsakura requested changes
- фильтры вынеси под products/filter
- цены под products/price
- продукты под products/product

2024-11-01 08:33 UTC, DanielGreenEngineer commented
> * фильтры вынеси под products/filter
> * цены под products/price
> * продукты под products/product

Переместил все модели по пакетам, чтобы безхозно их не бросать.

2024-11-01 08:34 UTC, DanielGreenEngineer commented
Забыл вчера пруф прицепить. 
<img width="1512" alt="Screenshot 2024-10-31 at 12 47 50 PM" src="https://github.com/user-attachments/assets/c779f416-e5f2-4a90-a9ff-8f31c4a3d219">

2024-11-01 09:37 UTC, TorinAsakura approved these changes

2024-11-01 09:37 UTC, merged