Feat/push notification
rees46/android-sdk pull request #73
Opened 2024-11-02 11:39 UTC by DanielGreenEngineer

- https://github.com/rees46/development/issues/206

2024-11-06 12:46 UTC, TorinAsakura requested changes

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
Очень странная структура выходит: notification/core/** в котором просто ВСЁ, и запрос кодов и уведомления. Быть может лучше core/${feature}/**/* раз уж на то пошло?

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +    var notificationType: String = "NOTIFICATION_TYPE"
Выглядит так, будто код не задумывался для многопоточного окружения. Представь, что уведомления с разными ID или типами начнут создаваться параллельно — нас ждёт весёлый концерт из перезаписываемых значений и рандомных багов. Используй локальные параметры или передавай значения через аргументы методов.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +    private val requestCodeGenerator = RequestCodeGenerator
Тут или совсем уж скрытая логика, или просто лень. Обычно такое можно сделать через последовательность AtomicInteger. А генерация request code у тебя вообще должна быть скрыта от всех и от вся, чтобы минимизировать шансы на рандомные коллизии.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +        val customView = RemoteViews(context.packageName, R.layout.custom_notification)
Вынеси код работы с RemoteViews в отдельные классы или хотя бы в хелпер-функции. У тебя тут чёткий намёк на нарушение SRP, когда NotificationHelper раздувается и решает всё: от создания уведомлений до навигации между изображениями. Каждая задача должна быть разделена, а не монолитный хелпер на все случаи жизни.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +    suspend fun loadBitmaps(urls: String?): List<Bitmap> {
Тут прям комбо: каждый URL скачивается поочерёдно в цикле, да ещё и в Dispatchers.IO. Накидать асинхронные вызовы с параллельной обработкой? Да, это было бы куда производительнее. Сделай это через async и awaitAll, чтобы не ограничивать скорость загрузки.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +                        SDK.error("Error caught in load bitmaps", ioException)
начни уже выносить это в слой errors отдельный

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +        data: Map<String, String?>,
Чрезмерное использование Map в качестве параметра (data: Map<String, String?>). Плюс это неудобно и кода раздувает, плюс ты не знаешь, что в этом Map хранится, пока не залезешь в каждое упоминание. Заведи data class — всё будет типизировано, красиво и с автокомплитом.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +            .setSmallIcon(R.drawable.ic_notification_logo)
Хардкод во всех проявлениях. ID ресурсов (R.drawable.ic_notification_logo и прочие) лучше выносить в отдельный класс-константу. Это и лучше для поддержки, и избегает необходимости лезть в код в случае изменений в ресурсах.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +        val prevPendingIntent = createNavigationPendingIntent(
Смешение UI и бизнес-логики. Какой-то дикий микс, где в одном классе одновременно создаются UI-компоненты и навешиваются PendingIntent. Код создания PendingIntent и вообще навигации по изображениям нужно вынести в отдельный класс, который знает только о навигации, а не о том, как UI выглядит.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +            context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
Отсутствие явного DI. Если ты используешь NotificationManager, передавай его через конструктор или какой-нибудь DI-контейнер, а не хардкодь через getSystemService. Учитывая, что это object, ты привязываешь вызовы NotificationManager к конкретной реализации, что сильно усложняет тестирование и поддержку.

2024-11-06 12:46 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +import android.widget.RemoteViews
Инициализация RemoteViews. Ты создаёшь объект с нуля каждый раз, но не факт, что он нужен таким образом. Если дизайн позволяет, можно создать шаблонный RemoteViews один раз и только обновлять его данные.

2024-11-07 14:47 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
У нас есть пакет фич, утащил туда и там разнес по пакетам.

2024-11-07 14:48 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +    var notificationType: String = "NOTIFICATION_TYPE"
Согласен. Заменил на передачу данных через конструктор.

2024-11-07 14:51 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +    private val requestCodeGenerator = RequestCodeGenerator
Добавил AtomicInteger в генератор. Я вроде его ранее добавлял уже, но почему то отказался в последствии. Но сейчас всё работает.

2024-11-07 14:52 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +        val customView = RemoteViews(context.packageName, R.layout.custom_notification)
Разбил хелпер на мелкие куски с соответствующими им задачами.

2024-11-07 14:52 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +    suspend fun loadBitmaps(urls: String?): List<Bitmap> {
Согласен. Заменил на асинк и корутины.

2024-11-07 14:53 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +                        SDK.error("Error caught in load bitmaps", ioException)
Завел отдельный класс под это и заменил все места с подобным.

2024-11-07 14:53 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +        data: Map<String, String?>,
Согласен. Завел модель и использовал её.

2024-11-07 14:53 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +            .setSmallIcon(R.drawable.ic_notification_logo)
Вынес в отдельный обьект ресурсов.

2024-11-07 14:54 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +        val prevPendingIntent = createNavigationPendingIntent(
Разделил в процессе разбивки монолита хенлера.

2024-11-07 15:10 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/notification/core/NotificationHelper.kt
> +import android.widget.RemoteViews
К сожалению нужен, я пробовал его единожды создать и реюзать, но из-за этого не работает карусель изображений. Думал докинуть проверку на наличие множества изображений, но даже в этом нет смысла, так как пересоздания не будет в этом случае, ведь не будет обновления пуша.

2024-11-08 13:33 UTC, TorinAsakura requested changes
короче, очередная порция фарша

2024-11-08 13:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/core/ErrorHandler.kt
> +object ErrorHandler {
нет-нет-нет и ещё раз нет! хендлеры должны жить отдельно, как и ошибки! я тебе когда пишу про "СЛОЙ" значит создаёшь рядом папку errors и туда кладёшь каждую ошибку как класс и потом их оттуда переиспользуешь, а это ты щас очередной комбайн собираешься делать…

2024-11-08 13:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/core/NotificationHandler.kt
> +package com.personalization.features.notification.core
что такое core в фиче уведомлений? я тебе сказал либо вынести кор наверх либо убрать его вовсе

2024-11-08 13:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/broadcast/NotificationBroadcastReceiver.kt
> +                ErrorHandler.logError("Error caught in onReceive because one of the fields is empty or null")
это вот всё разные классы ошибок, к примеру твой текущий кейс это errors/emptyField.error.kt и тд

2024-11-08 13:33 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/helpers/NotificationDataMapper.kt
> +object NotificationDataMapper {
что ещё за дэйта маппер?!

2024-11-11 14:56 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/core/ErrorHandler.kt
> +object ErrorHandler {
Вынес ошибки и хенделеры в отдельный слои.  Так же разделил ошибки.

2024-11-11 14:56 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/core/NotificationHandler.kt
> +package com.personalization.features.notification.core
Избавился от кор вовсе.

2024-11-11 14:56 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/broadcast/NotificationBroadcastReceiver.kt
> +                ErrorHandler.logError("Error caught in onReceive because one of the fields is empty or null")
Разделил ошибки и исправил в местах вызовов.

2024-11-11 14:57 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/helpers/NotificationDataMapper.kt
> +object NotificationDataMapper {
Маппер полей приходящих в пушах.

2024-11-11 21:12 UTC, TorinAsakura requested changes
По остальным, аналогичным кускам замечания из той же оперы

2024-11-11 21:12 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/broadcast/NotificationBroadcastReceiver.kt
1. Работа через BroadcastReceiver для навигации по уведомлению. Это архитектурный антипаттерн. BroadcastReceiver нужен для получения системных широковещательных сообщений или действий от других приложений, но использовать его для контроля навигации в уведомлениях — это что-то явно странное. Если задача ограничивается локальной навигацией по изображениям, правильнее было бы обойтись PendingIntent с передачей данных без создания таких промежуточных компонентов.
2. Злоупотребление WorkManager. WorkManager предназначен для фоновых задач, которые должны выживать при перезагрузках устройства и выполняться с учётом условий (например, при наличии сети или определённого уровня заряда). Использование его для обновления изображения в уведомлении, особенно в режиме OneTimeWorkRequest, выглядит как оверкилл. Это замедляет отклик и ненужный расход ресурсов.
3. Ошибки управления состоянием. Здесь валидация проверяет images, title, и body на null, но перед этим из них уже извлекаются значения. Если images пустой, это логически некорректное состояние, которое должно обрабатываться ещё до вызова этого ресивера. Лучше сделать валидацию на уровне вызова, а не на уровне обработки.
4. Обработка ошибок. В случаях EmptyFieldError и ActionsError ты просто логируешь ошибки, но не предпринимаешь других действий. Это может оставить приложение в неопределённом состоянии. Логи — это хорошо, но разумнее также обеспечить fallback или UI-уведомление, чтобы пользователи не сталкивались с бесконечными пустыми экранами и неработающими кнопками.
5. ExistingWorkPolicy.APPEND_OR_REPLACE для уникальной задачи. Этот подход не идеален. Сначала запросы добавляются в очередь, а затем заменяются при совпадении. Лучше использовать KEEP или продумать схему, исключающую лишние срабатывания.

2024-11-11 21:12 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/mapper/NotificationDataMapper.kt
1. Нарушение SRP. Маппер изначально задумывался для преобразования данных, а тут он ещё и занимается проверками на null и пустые значения, которые по-хорошему нужно обрабатывать в отдельной валидации. В идеале, маппер должен получать на вход уже валидные данные и не нести ответственности за корректность их содержимого.
2. Жёсткая привязка к Map. Использование Map<String, String> для хранения данных — это просто прямой путь к неявным багам. Стоит заменить это на более типизированную модель данных (например, NotificationData). Тогда можно избавиться от необходимости следить за строковыми ключами (NOTIFICATION_TITLE, NOTIFICATION_BODY) и явно работать с полями объекта.
3. MutableMap в возвращаемом значении. Ты возвращаешь MutableMap, что позволяет потенциально мутировать результат, что не всегда безопасно и предсказуемо. Если уж нужен Map, лучше придерживаться Map<String, String> и возвращать его как ImmutableMap, особенно если результат не должен изменяться после маппинга, о чём, я уже неоднократно писал в куче предыдущих ревью и, наверно, раз 200 (ну, 80 точно) в ревью Марии.
4. Методы-расширения или перегрузка функции. Вместо mapRemoteMessageToData нужно использовать функцию-расширение (екстендер/экстеншен) для RemoteMessage. Тогда это выглядело бы как remoteMessage.toNotificationData(), что читалось бы проще и инкапсулировало бы логику трансформации.

2024-11-11 21:12 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/worker/UpdateNotificationWorker.kt
## Проблемы
1. Нарушение принципов работы Worker. Воркер должен быть предназначен для фоновой задачи, которая требует долговременного выполнения или каких-то условий (например, Wi-Fi-соединения или заряда батареи). Здесь же воркер выполняет задачу, которая могла бы спокойно быть решена на UI-потоке или внутри основного процесса (например, обновление уведомления). Использование Worker для локального обновления уведомления — это оверкилл.
2. Архитектурный хаос. Воркер напрямую использует NotificationHelper и NotificationImageHelper, выполняя сразу несколько обязанностей — загрузку данных, создание уведомления, обработку ошибок. Всё это нарушает SRP. В идеале воркер должен только инициировать запросы и сообщать о завершении.
3. Неоптимальная работа с данными. Вместо того чтобы передавать весь текст и ссылки на изображения через inputData, нужно работать с NotificationData напрямую и хранить данные в типизированном объекте, передавая только его идентификатор.
4. Код загрузки изображений. Этот код загружает изображения синхронно, но вызывает NotificationHelper.createNotification сразу после их получения. Это просто тупо, потому как для загрузки картинок в фоновом потоке лучше использовать отдельный сервис, а воркер оставить для задачи контроля или триггера.
5. Ошибки с логированием. Ошибки через SDK.error и NetworkError только логируются, но без нормальной обработки ошибок. В случае неудачи лучше было бы попытаться повторить задачу или показать пользователю fallback (например, пустое изображение или уведомление без картинки), о чём я уже писал чуть выше.
6. Зависимость от контекста. Внутри doWork ты заново инициализируешь context, но applicationContext уже доступен из CoroutineWorker.

## Решение
1. Вынести логику загрузки изображений и создания уведомлений в отдельные сервисы или классы, не нагружая воркер.
2. Упрощённо хранить NotificationData и передавать его ID в inputData.
3. Если задача короткая и её можно выполнять быстро, заменить Worker на JobIntentService или другой подход.
4. Добавить обработку ошибок с retry и fallback.

2024-11-11 21:12 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/domain/helpers/NotificationClickHandler.kt
Это точно не хэндлер, по крайней мере в классическом понимании. Здесь скорее просто вспомогательный объект для обработки клика на уведомление, но до паттерна Handler он не дотягивает.

## Почему?

1. Отсутствие очереди и диспетчеризации событий. Паттерн Handler обычно подразумевает очередность обработки событий и часто используется для асинхронной передачи сообщений между потоками. В Android класс Handler связан с обработкой сообщений в Looper и управляет очередью, но тут ты просто обрабатываешь клик сразу. Так что “handler” в его названии сбивает с толку.
2. Смешение обязанностей. Метод handleNotificationClick сразу и парсит данные, и отправляет их асинхронно, и обрабатывает результат через onResult. Правильней было бы разделить задачи: пусть один класс отвечает за извлечение данных из Bundle, другой — за отправку данных асинхронно, и ещё один — за обработку результата.
3. Обработка ошибок. Если extras не содержит нужных данных, метод просто возвращается, только не очень понятно зачем. Полезнее было бы явно обработать такие случаи или вернуть ошибку, чтобы вызывающий код знал, что что-то пошло не так, иначе у тебя получается просто чёрный ящик

2024-11-14 12:57 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/broadcast/NotificationBroadcastReceiver.kt
- В целом выкинул броадкаст ресивер и воркер, и перевел всё на сервис. 
- Добавил проверки полей до их использования во вью. 
- Добавил обработку ошибок насколько это позволительно, так как под пушем ничего толком видно не будет, но тост будет вылазить, а так же оставил логирование.

2024-11-14 13:03 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/mapper/NotificationDataMapper.kt
- Разбил маппер на мелкие части по подготовке, сбору и передачи данных. 
- Выбрасил мапу отовсюду, всё перевел на обьект нотификаций
- Согласен с икстеншеном, заменил маппинг на функцию и выкинул лишнюю связку из хендеров

2024-11-14 13:05 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/data/worker/UpdateNotificationWorker.kt
- Первоначальная загрузка изображений происходит вне сервиса, последующая из сервиса, чтобы не городить очередной ресивер для передачи данных
- Все данные из пуша теперь в NotificationData и гуляют вместе с модулем DI
- Добавил обработку насколько это приемлемо на мобилке и обозримо пользователем

2024-11-14 13:06 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/features/notification/domain/helpers/NotificationClickHandler.kt
Разбил хендлер как уже писал выше и добавил обработки и отображение ошибок с возможностью перезагрузки данных.

2024-11-14 15:14 UTC, TorinAsakura approved these changes

2024-11-14 15:15 UTC, merged