feat: Added param for reinitialization sdk
rees46/android-sdk pull request #79
Opened 2024-12-02 12:53 UTC by DanielGreenEngineer

- https://github.com/rees46/development/issues/2110

2024-12-02 22:24 UTC, TorinAsakura requested changes

2024-12-02 22:24 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/RegisterManager.kt
> +        if (did.isNullOrEmpty()) {
опять же - не смешивай

2024-12-03 11:13 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/RegisterManager.kt
> +        if (did.isNullOrEmpty()) {
Видел коменты в прошлом PR, вернул проверку на пустоту, убрал ретёрн нулл и оставил сугубо проверку на флаг или на пустое значение

2024-12-03 14:17 UTC, TorinAsakura approved these changes

2024-12-03 14:17 UTC, merged