feat: stories - add text blocks
rees46/android-sdk pull request #8
Opened 2024-05-24 17:28 UTC by xeewii

2024-05-28 12:00 UTC, TorinAsakura requested changes

2024-05-28 12:00 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/StoryItemView.java
1. **Инкапсуляция**:
Большинство полей класса StoryItemView являются публичными, что нарушает принцип инкапсуляции. Следует сделать их private и добавить геттеры/сеттеры по мере необходимости.

2. **Отсутствие явной инициализации**:
Поля класса инициализируются в методе init(), что может быть неочевидным для других разработчиков. Лучше инициализировать их в конструкторе или сразу при объявлении.

3. **Магические числа**:
В коде много "магических чисел" (например, 100, 200), которые лучше вынести в константы с понятными именами.

4. **Дублирование кода**:
Много логики, связанной с настройкой текста, может быть вынесено в отдельные методы для уменьшения дублирования кода:
- setupButton
- setupTextBlock
- updateElements

2024-05-28 16:18 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/Story.java
6. **Моноспецифичный конструктор:**
Не совсем понимаю, что здесь имелось в виду. В плане создавать разные типы элементов в зависимости от поступаемого типа, например?

2024-05-28 16:52 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/Story.java
Речь шла о том, что текущий конструктор класса StoryItemView обрабатывает создание всех элементов слайдов (например, "button", "text_block" и т.д.) в одном месте

2024-05-29 10:25 UTC, xeewii commented on personalizatio-sdk/build.gradle
> +version='1.8.19'
Откатила

2024-05-29 11:24 UTC, TorinAsakura requested changes
с инкапсуляцией мы справились, осталось немного использование языка подтьюнить и можно катиться, а там уже и рефакториться на котлин

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +    public TextBlockElement(@NonNull JSONObject json) throws JSONException {
Обработка исключений: Сейчас исключение JSONException просто пробрасывается. Лучше обрабатывать его, чтобы можно было понять, где произошла ошибка.

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +    public Boolean isBold() {
Используй примитивные типы они занимают меньше памяти и проще в использовании

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +    public String toString() {
Используй String.format

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +        if (json.has("bold")) {
зачем ты повторяешь извлечение json? Не быстрее ли будет через json.Opt?

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/ProductsElement.java
> +    private String labelHide;
Использование значений по умолчанию для строковых полей labelHide и labelShow решает задачу nullSafety, во всех остальных кусках проблемы того же характера

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/Slide.java
> +    private Element createElement(JSONObject json) throws JSONException {
вроде бы статик, не?

2024-05-29 11:24 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/Slide.java
> +    private final int DEFAULT_DURATION_SECONDS = 5;
статик?

2024-05-29 23:05 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +    public TextBlockElement(@NonNull JSONObject json) throws JSONException {
Изменила получение полей json'а с помощью json.Opt, добавила дефолтные значения, и исключение ушло за ненадобностью

2024-05-29 23:05 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +    public Boolean isBold() {
проглядела - поправила

2024-05-29 23:05 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +    public String toString() {
Изменила

2024-05-29 23:05 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/Slide.java
> +    private Element createElement(JSONObject json) throws JSONException {
Изменила

2024-05-29 23:05 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/Slide.java
> +    private final int DEFAULT_DURATION_SECONDS = 5;
Изменила

2024-05-29 23:06 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/ProductsElement.java
> +    private String labelHide;
Изменила

2024-05-29 23:06 UTC, xeewii commented on personalizatio-sdk/src/main/java/com/personalizatio/stories/models/elements/TextBlockElement.java
> +        if (json.has("bold")) {
Изменила

2024-05-30 10:01 UTC, TorinAsakura commented
@xeewii теперь нужно создать задачу на обновление документации на @gochicu

2024-05-30 11:48 UTC, xeewii commented
> @xeewii теперь нужно создать задачу на обновление документации на @gochicus 

Не совсем понимаю как это описать в документации... И вообще в ней сейчас по сторисам есть только один пункт про общий шрифт, и больше ничего, то есть даже пример не посмотреть

2024-05-30 17:10 UTC, TorinAsakura commented
> > @xeewii теперь нужно создать задачу на обновление документации на @gochicus
> 
> @TorinAsakura Не совсем понимаю как это описать в документации... И вообще в ней сейчас по сторисам есть только один пункт про общий шрифт, и больше ничего, то есть даже пример не посмотреть

тебе - никак

@gochicus сам сделай таску

2024-05-30 17:11 UTC, merged