Feat/init with optional params
rees46/android-sdk pull request #83
Opened 2024-12-12 15:14 UTC by DanielGreenEngineer

-[Task](https://github.com/rees46/development/issues/2222)

2024-12-13 09:23 UTC, TorinAsakura requested changes

2024-12-13 09:23 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/SDK.kt
> +            url = apiDomain?.let { "https://$it/" }
у некоторых клиентов бывает криво настроен nginx и закрывающие слеши могут ломать работу - мы не должны зашивать это

2024-12-13 09:23 UTC, TorinAsakura commented on personalization-sdk/src/personaclick/kotlin/com/personaclick/sdk/Personaclick.kt
>  class Personaclick private constructor() : SDK() {
персону нужно выбросить из нашего СДК - новая таска

2024-12-13 14:19 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/SDK.kt
> +            url = apiDomain?.let { "https://$it/" }
Добавил  formatApiDomain, которая проверит, есть ли закрывающий слэш в apiDomain. Если он уже есть, ничего не добавляет. Если нет, добавляет слэш.

2024-12-14 09:50 UTC, TorinAsakura requested changes

2024-12-14 09:50 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/utils/DomainFormattingUtils.kt
> +}
```suggestion
object DomainFormattingUtils {

    private val URL_REGEX = Regex("^(https?://)?.+\\..+")

    fun formatApiDomain(apiDomain: String): String {
        require(apiDomain.isNotBlank()) { "API domain cannot be blank" }

        if (!URL_REGEX.matches(apiDomain)) {
            throw IllegalArgumentException("Invalid domain: $apiDomain")
        }

        val formattedDomain = if (!apiDomain.startsWith("http://") && !apiDomain.startsWith("https://")) {
            "https://$apiDomain"
        } else {
            apiDomain
        }

        return formattedDomain.trimEnd('/')
    }
}
```

2024-12-14 09:50 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/utils/DomainFormattingUtils.kt
> +}
Сейчас твоя утилита делают какую-то ересь:

---

- Если входящий `apiDomain` уже начинается с `https://` или `http://`, код **всё равно добавляет `https://`** в начале. Это очевидная ошибка.
- Если домен уже правильно форматирован (например, `https://xuy.nya/`), код добавит второй слеш в конце: `https://https://xuy.nya//`.
- Нет проверки на валидность входного `apiDomain`. Если передать мусор (`"example"`, `"ftp://xero-bora"`, `"1234"`), он всё равно добавит `https://`.
- Используются хардкодные строки типа `"https://"`, без явной возможности их настройки

---

### **Тесты**
Примеры тест-кейсов, которые нужно покрыть:

1. **Валидные входные данные**:
   - `"example.com"` → `"https://example.com"`
   - `"https://example.com"` → `"https://example.com"`
   - `"example.com/"` → `"https://example.com"`

2. **Необходимость добавления схемы**:
   - `"http://example.com"` → `"http://example.com"`
   - `"https://example.com"` → `"https://example.com"`

3. **Некорректные входные данные**:
   - `""` → `IllegalArgumentException: API domain cannot be blank`
   - `"ftp://example.com"` → `IllegalArgumentException: Invalid domain`

4. **Лишние слэши в конце**:
   - `"example.com////"` → `"https://example.com"`

2024-12-16 10:01 UTC, DanielGreenEngineer commented on personalization-sdk/src/main/kotlin/com/personalization/utils/DomainFormattingUtils.kt
> +}
Добавил тестирование. Модифицировал твой код, так как не всё верно обрабатывалось. Добавил описание утилите

2024-12-16 11:09 UTC, TorinAsakura approved these changes

2024-12-16 11:09 UTC, merged