Feat/add get client shopping cart api method
rees46/android-sdk pull request #86
Opened 2024-12-16 16:45 UTC by looee1q

* https://github.com/rees46/development/issues/718

2024-12-17 14:57 UTC, looee1q commented
![Issue_719](https://github.com/user-attachments/assets/8c053605-9d79-48a4-aab7-635897aef1df)

2024-12-17 17:00 UTC, looee1q commented
@TorinAsakura Здесь я тоже изначально не по форме назвал первый коммит. Мне его тоже переименовать? Это действие перезапишет историю коммитов и добавит сюда целую кучу лишних коммитов, как это получилось в [предыдущем ПР](https://github.com/rees46/android-sdk/pull/85)

2024-12-17 21:52 UTC, TorinAsakura requested changes

2024-12-17 21:52 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +        listener: OnApiCallbackListener?
колбэк в асинке хреновая практика, юзай саспенд и можешь использовать `result<T>` для безопасности

2024-12-17 21:52 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +    fun getClientShoppingCart(
Что такое getClientShoppingCart? Возвращает данные? Логирует? Модифицирует? Достаточно ли одной операции, или это часть более крупного набора методов? - если коротко - то не ясна зона ответственности

2024-12-17 21:52 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +    fun getClientShoppingCart(
Я также требую использовать jdoc для описания классов/функций

2024-12-17 21:52 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +import com.personalization.api.OnApiCallbackListener
Если интерфейс OnApiCallbackListener широко используется и привязан к старому API, это говорит об "протечке" абстракции. Любое изменение в OnApiCallbackListener затронет все реализации CartManager.

2024-12-17 21:52 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +            method = GET_CLIENT_SHOPPING_CART,
GET_CLIENT_SHOPPING_CART вынеси константу наверх, поищи в проекте constants или типа того

2024-12-17 21:52 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +    private val sendNetworkMethodUseCase: SendNetworkMethodUseCase,
Плохое именование sendNetworkMethodUseCase
- слишком абстрактно и не отражает суть
- Назови осмысленно, чот типа: fetchCartUseCase или getCartDataUseCase, иначе вообще не понятно, что за "ОтправкаСетевогоМетодаЮзКейс" - слишком много вопросов возникает при чтении

2024-12-18 08:10 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +        listener: OnApiCallbackListener?
Сейчас в проекте все обращения к Rees Api идут через подобные менеджеры, а результат возвращается в виде колбека. Для того, чтобы перейти к использованию корутин (suspend функций) нужно полностью переделать всю работу с сетью. Например перейти к использованию наиболее популярной для таких дел библиотеке [Retrofit](https://square.github.io/retrofit/), которая внутри себя огранизует всю работу по ассинхронности и возвращает результат уже в виде конкретного класса (позволяя при этом в том числе заниматься обработкой ошибок).

2024-12-18 08:11 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +    fun getClientShoppingCart(
Назвал метод так же, как он называется у нас в [документации](https://reference.api.rees46.com/?kotlin#get-client-39-s-shopping-cart).

2024-12-18 08:31 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +            method = GET_CLIENT_SHOPPING_CART,
В проекте большинство констант описываются в companion object, который находится внизу класса, которому нужна это константа.

2024-12-18 08:36 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +    private val sendNetworkMethodUseCase: SendNetworkMethodUseCase,
Класс [SendNetworkMethodUseCase](https://github.com/rees46/android-sdk/blob/a26b664519bee1b792092aebc19d2f9338b99a03/personalization-sdk/src/main/kotlin/com/personalization/sdk/domain/usecases/network/SendNetworkMethodUseCase.kt#L8) используется для работы с сетью. 
И все классы менеджеров и сам класс SDK обращаются к SendNetworkMethodUseCase для выполнения сетевых запросов к Rees Api.

2024-12-18 10:40 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +    fun getClientShoppingCart(
Добавил.

2024-12-18 11:15 UTC, looee1q commented
Подверждение правильности работы метода после нового коммита:

![Issue_719_new](https://github.com/user-attachments/assets/b68a5a4b-1a90-4f02-88fc-8f9819c43ec9)

2024-12-18 20:47 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +        listener: OnApiCallbackListener?
Поищи на эту тему таски, я бывшей падаванше давал задание переработать взаимодействие с сетью, что-то заводили вроде. Если не найдёшь - давай делать таску и последовательно избавляться от этого бардака. Ретрофит нам не подойдёт так как помимо реста мы будем использовать WS, gQL, так что тут только ктор, а заодно мы сможем начать идти в сторону KMP (давно уже пора перестать писать одну и ту же бизнесуху на разных языках)

2024-12-18 21:06 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +            method = GET_CLIENT_SHOPPING_CART,
всё просто - если штука локальная - можно наверх
если штука системная - в ./className.constants.kt

2024-12-18 21:07 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +            method = GET_CLIENT_SHOPPING_CART,
компаньон - древний паттерн лишённый гибкости, я ещё весной сказал от него избавляться

2024-12-18 21:09 UTC, TorinAsakura requested changes
жду последних правок

2024-12-18 21:09 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +}
последняя строка

2024-12-19 09:41 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +        listener: OnApiCallbackListener?
Созданной таски не нашел, поэтому создал новую:
- https://github.com/rees46/development/issues/2260

2024-12-19 09:51 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +            method = GET_CLIENT_SHOPPING_CART,
Исправил.

Можешь, пожалуйста, подсказать, точно ли паттерн называется компаньон? По крайней мере в мире устоявшихся design patterns такого нет и при гуглении тоже ничего путного не попадается.

И если есть возможность объяснить, в чем заключаются недостатки описания констант в `companion object`, то тоже будет здорово. Ведь по сути константа объявленная внутри `companion object` - аналог статических полей в Java. И именно таким образом в Java часто задаются локальные для класса константы.
Ну и в целом с точки зрения `byte кода` практически нет разницы между объявлением констаны в `companion object` или в качестве `top-level property`.

2024-12-19 11:01 UTC, TorinAsakura approved these changes

2024-12-19 11:06 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/features/cart/CartManagerImpl.kt
> +            method = GET_CLIENT_SHOPPING_CART,
а мы разве занимаемся разработкой байт кода? мы делаем продукт и не только для потребителей но и для себя

с константами удобней работать, их можно выносить за пределы класса, класть в зависимости через тот же диай с компаньоном такие фокусы не пройдут

Насчёт компаньона - странно, всегда считал его паттерном, но, нет, оказалось что это не паттерн, а просто синтаксический сахар, что впрочем не отменяет его проблем, так как часто (почти всегда) компаньон перегружают лишними обвесами и происходит нарушение SRP

2024-12-19 11:07 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/api/managers/CartManager.kt
> +        listener: OnApiCallbackListener?
> Созданной таски не нашел, поэтому создал новую:
> 
> * [Ktor migrating development#2260](https://github.com/rees46/development/issues/2260)

https://github.com/rees46/development/issues/1483 плохо искал
эту нужно в таком случае поглотить сославшись на твою таску

2024-12-19 11:08 UTC, merged