Refactor/adding data sources abstractions
rees46/android-sdk pull request #87
Opened 2024-12-18 16:29 UTC by looee1q

- https://github.com/rees46/development/issues/1510

2024-12-20 08:58 UTC, looee1q commented
Заметки:
1. Работа с сегментом (segment) для A/B тестирования. При каждом входе в приложение генерируется новое значение сегмента случайным образом. При этом значение сегмента не сохраняется в sharedPreferences (такого метода просто не существует в [PreferencesDataSource](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/preferences/PreferencesDataSource.kt#L7C7-L7C28)). Так и должно быть?
2. [Такое дублирование](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/SDK.kt#L629) комментариев нормально? Если да, то зачем они дублируются?
3. Почему внутри рабочих функций (не являющихся deprecated) используются deprecated фунции? Вот пример: внутри функции [profile()](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/SDK.kt#L215) используется deprecated функция [sendAsync()](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/SDK.kt#L266).

2024-12-24 20:45 UTC, TorinAsakura commented
> @TorinAsakura В ходе работы над этой таской выявил следующие моменты, которые хотелось бы подстветить. Они же служат обоснованием почему я написал код именно так.
> 
> 1. Текущий [NetworkDataSource](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/network/NetworkDataSource.kt#L7) по сути является оберткой для `baseUrl`. Полагаю, цель внедрения NetworkDataSource была все-таки другой. Вероятно в этом классе должна происходить настройка инструмента для работы с сетью. А [NetworkRepositoryImpl](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/network/NetworkRepositoryImpl.kt#L28) должен опираясь на этот инструмент образовывать функции, не зависящие от того, каким конкретно будет инструмент для работы с сетью, и предоставлять их UseCase(ам) и дальше в SDK. Текущая реализация `NetworkDataSource` на мой взгляд не имеет никакого смысла. Я бы занялся отделением кода `NetworkRepositroy` от `NetworkDataSource` при внедрении `Ktor`. А на данном этапе просто удалил `NetworkDataSource`.
> 2. [Тут](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/SDK.kt#L629) случайно продублировали jdoc. Удалил лишние комментарии.
> 3. Почему внутри рабочих функций (не являющихся `deprecated`) используются `deprecated` фунции? Вот пример: внутри функции [profile()](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/SDK.kt#L215) используется deprecated функция [sendAsync()](https://github.com/rees46/android-sdk/blob/fcc159117d985510f27e11af9a6cf92413d8158c/personalization-sdk/src/main/kotlin/com/personalization/SDK.kt#L266). Такого ведь нельзя допускать?
> 
> Дополнительно еще вынес два момента в дисуссии для обсуждения.

1. Всё так. Поддерживаю.
3. Конечно же нельзя. Сжечь их…Сжечь их всех!

2024-12-24 21:03 UTC, TorinAsakura requested changes

2024-12-24 21:03 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    private var isInitialized: Boolean = false
это один из древнейших антипаттернов. Этот флаг добавляет состояние, которое легко забыть синхронизировать, более того, он не используется в данном коде, кроме геттеров/сеттеров.

Если флаг действительно необходим, лучше перенести его управление в отдельный класс или юзать лейзи

2024-12-24 21:03 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
тут у нас явное нарушение DIP

2024-12-24 21:03 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
Не вижу никакой(их) обработки ошибок

2024-12-25 09:38 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
Можешь подробнее рассказать, в чем конкретно тут нарушение DIP?
 
Сам принцип инверсии зависимости заключается в двух следующих концепциях:
- Сущности верхнего уровня не должны зависеть от сущностей нижнего уровня. 
- Абстракции не должны зависеть от реализаций. Реализации должны зависеть от абстракций.

И то и другое условие у нас выполняется:
- Внутри `UserSettingsDataSourseImpl` не создается вручную никаких сущностей. Зависимости, в виде абстракций (`PreferencesDataSource` и `String`) передаются внутрь конструктора (соблюдается первая концепция DIP).
- Реализация `UserSettingsDataSourceImpl` зависит от абстракции `UserSettingsDataSource`. Аналогично `PreferencesDataSourceImpl` зависит от `PreferencesDataSource` (соблюдается вторая концепция DIP).

2024-12-25 09:47 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> UserSettingsDataSrouce - вообще не понятный класс, за что он вообще отвечает и находится он при всё при этом аж в персистенс слое - много вопросов к этому куску.

Класс `UserSettingsDataSource` по своему замыслу и должен находится data-слое, поскольку соответствующий репозиторий делегирует на него свои полномочия. Для наглядности прикладываю схему зависимостей классов с подписанными слоями из `clean`.

Зачем класс `UserSettingsDataSource` вообще существует - вопрос хороший, ибо толку от него мало. Весь этот код можно по идее перенести напрямую в реализацию репозитория и не заниматься делегированием кода репозитория классу `DataSource`. Я не вижу какой-либо необходимости в этом классе. И не вижу никаких преимуществ его использования. Никто, кроме репозитория `UserSettingsRepositoryImpl` с этим классом не взаимодействует.

С радостью избавлюсь от этого класса, если скажешь это сделать.


![clean drawio](https://github.com/user-attachments/assets/8786f69a-6e2a-4f65-bcd9-a713df7538c2)

2024-12-26 08:21 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
Да, сноси

2024-12-26 08:23 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +private const val SID_LAST_ACT_KEY = "sid_last_act"
![Снимок экрана 2024-12-26 в 11 22 55](https://github.com/user-attachments/assets/19ca3b9d-acf2-4d68-86cc-d3490cdcfa33)

![Снимок экрана 2024-12-26 в 11 23 11](https://github.com/user-attachments/assets/c012e647-89eb-49e1-b4f5-6352df88739b)

2024-12-26 08:23 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun setIsInitialized(value: Boolean) {
ты если что-то меняешь - так хоть отписывайся

2024-12-26 08:25 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
Жёсткие зависимости через @AssistedInject
- Параметры shopId, segment и stream передаются через @AssistedInject, а это в свою очередь создаёт неявную связь с другими частями кода
- Эти зависимости усложняют тестирование и нарушают DIP

2024-12-26 12:15 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +private const val SID_LAST_ACT_KEY = "sid_last_act"
@TorinAsakura, давай сперва придем к соглашению об использованию констант.
Мы начинали об этом говорить, но из-за плохой связи, не получилось обсудить полностью.

Суть в том, что если мы выносим константы в отдельный файл, то их видимость сразу становится public.
Констант у нас очень много. Соответственно возникает ситуация, что из абсолютно разных мест кода мы сможем получить доступ к любой константе, что может способствовать путаннице.

Что не так с объявлением локальных для файла костант как топ-левел проперти этого файла?

2024-12-26 12:35 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
> Жёсткие зависимости через @AssistedInject
> - Параметры shopId, segment и stream передаются через @AssistedInject, а это в свою очередь создаёт неявную связь с другими частями кода
> - Эти зависимости усложняют тестирование и нарушают DIP

Аннотация `@AssistedInject` используется с той целью, чтобы параметры конструктора могли передаваться вручную (динамически) во время выполнения. Дополнительно, каждый из параметров конструктора помечен аннотацией, чтобы Dagger мог различать эти парамеры (ибо они все одного типа - String). 
По сути это вынужденная мера из-за использования статического DI инструмента.

Если мы уберем аннотацию, то в DI модулях, в которых описывается как создать класс, нам придется вручную захардкодить какое-то значение для этих параметров конструктора, чтобы Dagger умел создавать экземпляр класса.

В целом ведь введение параметра в конструктор класса в виде String не нарушает DIP. Или я неправ?

Еще я не очень понимаю, какую неявную связь с другими частями кода ты имешь ввиду:

> - Параметры shopId, segment и stream передаются через @AssistedInject, а это в свою очередь создаёт неявную связь с другими частями кода

2024-12-26 12:36 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun setIsInitialized(value: Boolean) {
> Я еще не успел доделать, поэтому не комментировал

2024-12-26 14:51 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +private const val SID_LAST_ACT_KEY = "sid_last_act"
Я не сказал, что с ними что-то не так, если андройд нас в этом ограничивает (в чём я сомневаюсь, как и про глобальную доступность констант вне контекста) - ради кода, можешь оставить как есть

2024-12-26 14:57 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
Ситуация сложилась спорная, но по пунктам:

1. **Жёсткие зависимости через `@AssistedInject`**:
   - Ты прав в том, что использование `@AssistedInject` для передачи параметров (например, `shopId`, `segment`, `stream`) действительно создаёт явную связь конструктора с вызывающим кодом, одакно нарушает принцип DIP, так как класс начинает зависеть от деталей, которые ему передают

2. **Непонимание выгоды `@AssistedInject`**:
   - Ты утверждаешь, что `@AssistedInject` используется для создания экземпляров с переменными параметрами, где Dagge сам по себе не может их предоставить. Это корректно. Но **если эти параметры неизбежны для бизнес-логики**, то этот подход имеет место быть, но, как исключение, а не норма.
   - Проблема в том, что в данном случае `shopId`, `segment`, и `stream` не являются чем-то, что DI не может решить — они не динамически изменяемые сущности.

3. **Резюме**:
   - Если параметры являются частью бизнес-логики, лучше передавать их через конфигурацию (например, через фабрику, а не через `@AssistedInject`).
   - Если параметры действительно динамически передаются из контекста выполнения, использование `@AssistedInject` допустимо.

2024-12-28 14:30 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
@TorinAsakura А может быть значения `shopId` и `segment` будем сохранять каждый раз при инициализации SDK в `SharedPref`/`EncryptedSharedPref`? Тогда во всех местах приложения, где они нужны, можно будет их брать из `SharedPref`/`EncryptedSharedPref`, а не прокидывать в качестве аргументов в конструкторы классов или функций.
Аналогично предлагаю хранить значение `base_url`.

А значение `stream` вообще можно задать констаной компиляции, поскольку для андройда это значение будет всегда равно `"android"`.

2024-12-28 14:53 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
Ничего против не имею, но такое понятие как Pref - нужно девуалировать, так как что такое Pref мне не смог даже объяснить человек, который всё это закладывал…

2025-01-09 12:38 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
Удалил `UserSettingsDataSource`/`UserSettingsDataSourceImpl` классы. 
Теперь методы получения и обновления базовых параметров HTTP запроса (таких как `did`, `sid`, `shop_id`, `segment`, `stream`) происходят через `UserSettingsRepository`.
При этом метод по добавлению этих параметров в итоговую JSON-строку HTTP запроса перенесен из `UserSettingsRepository` в `NetworkRepositoryImpl`.

2025-01-09 12:57 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun setIsInitialized(value: Boolean) {
Назначение `UserSettingsRepository` - получение значений базовых параметров HTTP запроса (таких как `did`, `sid`, `shop_id`, `segment`, `stream`) и их обновление.
Метод по формированию JSON-строки HTTP запроса с этими параметрами убрал из `UserSettingsRepository` и перенес в `NetworkRepositoryImpl`.

2025-01-09 13:03 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    private val preferencesDataSource: PreferencesDataSource,
`PreferencesDataSource` - и есть интерфейс, его реализация обеспечивает работу с `SharedPreferences` (сохранение туда значений параметров `sid`, `did`, `shop_id` и т.д. и получение их оттуда).

Класс `UserSettingsDataSourceImpl` удален. Его логика находится внутри класса `UserSettingsRepositoryImpl`, который работает с доменным слоем через интерфейс `UserSettingsRepository`.

2025-01-09 13:05 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    private var isInitialized: Boolean = false
Согласен. Класс `UserSettingsDataSourceImpl` удален. Так же удалил метод `initialize` из `UserSettingsRepository`.

2025-01-09 13:33 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    @Assisted("stream") private val stream: String
`SharedPreferences` (сокращенно `SharedPref` ) - механизм в Android для сохранения и извлечения данных в формате ключ-значение.
При этом записывать можно только примитивы и строки.
При работе с `SharedPref` создается отдельный XML-файл, куда и сохраняются пары "ключ-значения". Этот файл создается в приватной директории приложения и доступ к нему имет либо само приложение, его создавшее, либо приложение с правами root.

При этом не рекомендуется использовать `SharedPref` для чувствительной информации. Для шифрования данных и защиты данных можно использовать `EncryptedSharedPreferences`. Полагаю, что `shop_id` следует хранить именно в зашифрованном виде.

Вот так этот файл выглядит в нашем случае:

![image](https://github.com/user-attachments/assets/b1632179-af97-4771-b90d-dec62419034f)

2025-01-09 14:22 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun setIsInitialized(value: Boolean) {
Репозиторий должен управлять только сохранением, чтением, удалением данных (например, из базы данных, кеша, или API). Он не должен решать, какие данные и зачем нужны для HTTP-запросов.

2025-01-10 06:36 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun setIsInitialized(value: Boolean) {
Действительно работа с сетью и формирование HTTP запросов должны быть вынесены из `репозитория` в некоторый `ApiHander класс`. При этом реализация этого класса при работе, например, с `ретрофитом` ложится на плечи самого ретрофита, мы лишь описываем интерфейс и при помощи аннотаций показываем как должны выполняться запросы. В `Ktor` полагаю примерно аналогичная ситуация.

В нашем же SDK вся работа с сетью ложилась именно на `NetworkRepository`. А операции по присоединению основных парамеров HTTP запроса выполнялись вообще в `UserSettingsRepository` (при этом логика по присоединению остальных парамеров была реализована внутри `NetworkRepository`). Я решил внутри `UserSettingsRepository` оставить только логику по сохранению и получению значений базовых параметров HTTP запроса, и убрать оттуда логику по добавлению к HTTP запросу этих базовых параметров.

Касаемого того, что я считаю **репозиторием**. Вот [описание репозитория](https://developer.android.com/topic/architecture#data-layer) с официальной доки:

![image](https://github.com/user-attachments/assets/9348de91-9def-4b55-9b4d-f1e3641dc7c1)

Такого описания я и придерживаюсь. Разве что бизнес логика все же больше в domain-слое должна находится (просто не в каждом приложении имеется domain-слой).

В своем предыдущем комментарии я не очень корректно описал, что в репозитории должны формироваться запросы к API. Конечно надо переносить работу по формированию HTTP запросов из репозитория в отдельный класс, как это [описывается в доке](https://developer.android.com/topic/architecture/data-layer#network-request).

Но кажется эту таску лучше инкапсулировать в отдельную, потому что класс репозитория большой.

2025-01-10 13:41 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun addParams(
Методы по формированию JSON строки из переданных параметров вынес в отдельный [утилитарный объект](https://github.com/rees46/android-sdk/blob/ba83c2b7762d9c418601409845091236c685dd81/personalization-sdk/src/main/kotlin/com/personalization/sdk/data/utils/QueryParams.utils.kt#L5) с видимостью internal (т.е. он недоступен за пределами SDK).

Само формирование строки с указанными методами сейчас пока происходит в [репозитории](https://github.com/rees46/android-sdk/blob/ba83c2b7762d9c418601409845091236c685dd81/personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/network/NetworkRepositoryImpl.kt#L182).
Вынос этой логики в отдельный класс предлагаю сделать отдельной задачей.

Вообще переход от использования JSONObject к data-классам, выполняющих роль DTO вероятно стоит сделать. Но сейчас у нас вообще везде используются JSONObject при работе с сетью.
Поэтому переход от использования JSONObject к DTO совместно с каой-нибудь библиотекой для конвертации DTO в JSON (я предлагаю kotlinx.serialization) на мой взгляд стоит осуществлять комплексно и в рамках отдельной задачи

2025-01-10 16:19 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun setIsInitialized(value: Boolean) {
А я и не просил это делать здесь. Здесь мы должны были прийти к текущему состоянию. Выноси в отдельную таску.

2025-01-10 16:20 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsDataSourceImpl.kt
> +    override fun addParams(
Само собой в отдельной. Не нужно создавать замес в коде, в котором и так замеса хватает)

2025-01-10 18:53 UTC, TorinAsakura requested changes

2025-01-10 18:53 UTC, TorinAsakura commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsRepositoryImpl.kt
> +private const val DEFAULT_ADVERTISING_ID = "00000000-0000-0000-0000-000000000000"
ПРом ранее мы это переносили на UUID

2025-01-10 19:53 UTC, looee1q commented on personalization-sdk/src/main/kotlin/com/personalization/sdk/data/repositories/userSettings/UserSettingsRepositoryImpl.kt
> +private const val DEFAULT_ADVERTISING_ID = "00000000-0000-0000-0000-000000000000"
Исправил.
Пришлось способ создания дефолтного значения ADVERTISING_ID вынести в отдельный файл, чтобы можно было переиспользовать в двух различных классах.

2025-01-11 15:51 UTC, TorinAsakura approved these changes

2025-01-11 15:52 UTC, merged